# Generated by Django 4.2.7 on 2025-11-25 11:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('nivel_experto', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpredict.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('resultado_final', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('liga', models.CharField(blank=True, max_length=100)),
                ('temporada', models.CharField(default='2025-2026', max_length=50)),
                ('goles_local', models.IntegerField(blank=True, help_text='Goles o puntos del equipo local', null=True)),
                ('goles_visitante', models.IntegerField(blank=True, help_text='Goles o puntos del equipo visitante', null=True)),
                ('amarillas_local', models.IntegerField(blank=True, help_text='Tarjetas amarillas equipo local (fútbol)', null=True)),
                ('amarillas_visitante', models.IntegerField(blank=True, help_text='Tarjetas amarillas equipo visitante (fútbol)', null=True)),
                ('rojas_local', models.IntegerField(blank=True, help_text='Tarjetas rojas equipo local (fútbol)', null=True)),
                ('rojas_visitante', models.IntegerField(blank=True, help_text='Tarjetas rojas equipo visitante (fútbol)', null=True)),
                ('expulsiones_local', models.IntegerField(blank=True, help_text='Expulsiones por falta equipo local (baloncesto)', null=True)),
                ('expulsiones_visitante', models.IntegerField(blank=True, help_text='Expulsiones por falta equipo visitante (baloncesto)', null=True)),
                ('mvp_jugador', models.CharField(blank=True, help_text='Nombre del MVP del partido', max_length=100, null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='sportpredict.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='sportpredict.equipo')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('pred_goles_local', models.IntegerField(blank=True, help_text='Predicción goles/puntos equipo local', null=True)),
                ('pred_goles_visitante', models.IntegerField(blank=True, help_text='Predicción goles/puntos equipo visitante', null=True)),
                ('pred_amarillas_local', models.IntegerField(blank=True, help_text='Predicción amarillas equipo local', null=True)),
                ('pred_amarillas_visitante', models.IntegerField(blank=True, help_text='Predicción amarillas equipo visitante', null=True)),
                ('pred_rojas_local', models.IntegerField(blank=True, help_text='Predicción rojas equipo local', null=True)),
                ('pred_rojas_visitante', models.IntegerField(blank=True, help_text='Predicción rojas equipo visitante', null=True)),
                ('pred_expulsiones_local', models.IntegerField(blank=True, help_text='Predicción expulsiones equipo local', null=True)),
                ('pred_expulsiones_visitante', models.IntegerField(blank=True, help_text='Predicción expulsiones equipo visitante', null=True)),
                ('pred_mvp_jugador', models.CharField(blank=True, help_text='Predicción del MVP', max_length=100, null=True)),
                ('puntos_resultado', models.IntegerField(default=0, help_text='Puntos por acertar resultado')),
                ('puntos_tarjetas', models.IntegerField(default=0, help_text='Puntos por acertar tarjetas/expulsiones')),
                ('puntos_mvp', models.IntegerField(default=0, help_text='Puntos por acertar MVP')),
                ('puntos_totales', models.IntegerField(default=0, help_text='Puntos totales de esta predicción')),
                ('evaluada', models.BooleanField(default=False, help_text='Si ya se calcularon los puntos')),
                ('prediccion', models.CharField(blank=True, help_text='[LEGACY] Predicción simple antigua', max_length=10)),
                ('puntos_obtenidos', models.IntegerField(default=0, help_text='[LEGACY] Alias de puntos_totales')),
                ('correcta', models.BooleanField(default=False, help_text='[LEGACY] Si acertó completamente')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpredict.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_prediccion'],
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
